In [5]:
file = r'/Users/teslim/TeslimWorkSpace/WorkSpaceDataSources/SundryDataSources/Retail Transaction Loyalty Discount Report.xlsx'

In [2]:
import pandas as pd

df = pd.read_excel(file)

NameError: name 'file' is not defined

In [7]:
df

,TransactionID,Timestamp,CustomerID,Name,Surname,Shipping_State,Item,Description,Retail_Price,Loyalty_Discount
0,113255,2016-12-13 18:05:37,200000663,Leonard,Jackson,Delaware,8619953091,Pillowcase,18.96,0.02
1,113254,2016-12-13 18:05:22,200000661,Lucas,Abraham,Louisiana,2020397001,Men's Pajama Set,23.10,0.00
2,113253,2016-12-13 18:03:57,200000662,Trevor,Skinner,Louisiana,4681342313,Sheets,29.90,0.10
3,113252,2016-12-13 18:01:45,100000007,Dorothy,Thomson,Alabama,6697166886,Coat,159.80,0.07
4,113251,2016-12-13 18:01:22,400000180,Eric,Bower,New Hampshire,6697166886,Coat,159.80,0.06
...,...,...,...,...,...,...,...,...,...,...
3450,109805,2016-12-10 18:08:49,200000662,Trevor,Skinner,Louisiana,4619440506,Shorts,69.75,0.10
3451,109804,2016-12-10 18:08:36,100000854,Carl,Clark,Kentucky,5153370805,Shorts,43.96,0.02
3452,109803,2016-12-10 18:08:24,200000793,Charles,McDonald,Utah,3123824581,Sweatpants,43.89,0.06
3453,109802,2016-12-10 18:08:03,200000263,Gabrielle,Marshall,Michigan,9195451761,Hand Towel,51.66,0.07
3454,109801,2016-12-10 18:07:25,200000670,Richard,Carr,Louisiana,6660530324,Washcloth,35.14,0.05

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3455 entries, 0 to 3454
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   TransactionID     3455 non-null   int64
 1   Timestamp         3455 non-null   datetime64[ns]
 2   CustomerID        3455 non-null   int64
 3   Name              3455 non-null   object
 4   Surname           3455 non-null   object
 5   Shipping_State    3455 non-null   object
 6   Item              3455 non-null   int64
 7   Description       3455 non-null   object
 8   Retail_Price      3455 non-null   float64
 9   Loyalty_Discount  3455 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(3), object(4)
memory usage: 270.1+ KB

In [9]:
# clean the column_headers

def clean_columns_header(df):
    df.columns = df.columns.str.lower()
    df.columns = df.columns.str.strip()
    df.columns = df.columns.str.replace(" ", "_")
    return df

clean_columns_header(df)

,transactionid,timestamp,customerid,name,surname,shipping_state,item,description,retail_price,loyalty_discount
0,113255,2016-12-13 18:05:37,200000663,Leonard,Jackson,Delaware,8619953091,Pillowcase,18.96,0.02
1,113254,2016-12-13 18:05:22,200000661,Lucas,Abraham,Louisiana,2020397001,Men's Pajama Set,23.10,0.00
2,113253,2016-12-13 18:03:57,200000662,Trevor,Skinner,Louisiana,4681342313,Sheets,29.90,0.10
3,113252,2016-12-13 18:01:45,100000007,Dorothy,Thomson,Alabama,6697166886,Coat,159.80,0.07
4,113251,2016-12-13 18:01:22,400000180,Eric,Bower,New Hampshire,6697166886,Coat,159.80,0.06
...,...,...,...,...,...,...,...,...,...,...
3450,109805,2016-12-10 18:08:49,200000662,Trevor,Skinner,Louisiana,4619440506,Shorts,69.75,0.10
3451,109804,2016-12-10 18:08:36,100000854,Carl,Clark,Kentucky,5153370805,Shorts,43.96,0.02
3452,109803,2016-12-10 18:08:24,200000793,Charles,McDonald,Utah,3123824581,Sweatpants,43.89,0.06
3453,109802,2016-12-10 18:08:03,200000263,Gabrielle,Marshall,Michigan,9195451761,Hand Towel,51.66,0.07
3454,109801,2016-12-10 18:07:25,200000670,Richard,Carr,Louisiana,6660530324,Washcloth,35.14,0.05

In [10]:
df.columns.to_list()

['transactionid',
 'timestamp',
 'customerid',
 'name',
 'surname',
 'shipping_state',
 'item',
 'description',
 'retail_price',
 'loyalty_discount']

In [11]:
df

,transactionid,timestamp,customerid,name,surname,shipping_state,item,description,retail_price,loyalty_discount
0,113255,2016-12-13 18:05:37,200000663,Leonard,Jackson,Delaware,8619953091,Pillowcase,18.96,0.02
1,113254,2016-12-13 18:05:22,200000661,Lucas,Abraham,Louisiana,2020397001,Men's Pajama Set,23.10,0.00
2,113253,2016-12-13 18:03:57,200000662,Trevor,Skinner,Louisiana,4681342313,Sheets,29.90,0.10
3,113252,2016-12-13 18:01:45,100000007,Dorothy,Thomson,Alabama,6697166886,Coat,159.80,0.07
4,113251,2016-12-13 18:01:22,400000180,Eric,Bower,New Hampshire,6697166886,Coat,159.80,0.06
...,...,...,...,...,...,...,...,...,...,...
3450,109805,2016-12-10 18:08:49,200000662,Trevor,Skinner,Louisiana,4619440506,Shorts,69.75,0.10
3451,109804,2016-12-10 18:08:36,100000854,Carl,Clark,Kentucky,5153370805,Shorts,43.96,0.02
3452,109803,2016-12-10 18:08:24,200000793,Charles,McDonald,Utah,3123824581,Sweatpants,43.89,0.06
3453,109802,2016-12-10 18:08:03,200000263,Gabrielle,Marshall,Michigan,9195451761,Hand Towel,51.66,0.07
3454,109801,2016-12-10 18:07:25,200000670,Richard,Carr,Louisiana,6660530324,Washcloth,35.14,0.05

In [12]:
df.loc[: , ['name', 'surname', 'description', 'item', 'retail_price']]

           name   surname       description        item  retail_price
0       Leonard   Jackson        Pillowcase  8619953091         18.96
1         Lucas   Abraham  Men's Pajama Set  2020397001         23.10
2        Trevor   Skinner            Sheets  4681342313         29.90
3       Dorothy   Thomson              Coat  6697166886        159.80
4          Eric     Bower              Coat  6697166886        159.80
...         ...       ...               ...         ...           ...
3450     Trevor   Skinner            Shorts  4619440506         69.75
3451       Carl     Clark            Shorts  5153370805         43.96
3452    Charles  McDonald        Sweatpants  3123824581         43.89
3453  Gabrielle  Marshall        Hand Towel  9195451761         51.66
3454    Richard      Carr         Washcloth  6660530324         35.14

[3455 rows x 5 columns]

In [13]:
df.loc[:, ['item', 'retail_price']]

            item  retail_price
0     8619953091         18.96
1     2020397001         23.10
2     4681342313         29.90
3     6697166886        159.80
4     6697166886        159.80
...          ...           ...
3450  4619440506         69.75
3451  5153370805         43.96
3452  3123824581         43.89
3453  9195451761         51.66
3454  6660530324         35.14

[3455 rows x 2 columns]

In [14]:
df.loc[ :, :]

,transactionid,timestamp,customerid,name,surname,shipping_state,item,description,retail_price,loyalty_discount
0,113255,2016-12-13 18:05:37,200000663,Leonard,Jackson,Delaware,8619953091,Pillowcase,18.96,0.02
1,113254,2016-12-13 18:05:22,200000661,Lucas,Abraham,Louisiana,2020397001,Men's Pajama Set,23.10,0.00
2,113253,2016-12-13 18:03:57,200000662,Trevor,Skinner,Louisiana,4681342313,Sheets,29.90,0.10
3,113252,2016-12-13 18:01:45,100000007,Dorothy,Thomson,Alabama,6697166886,Coat,159.80,0.07
4,113251,2016-12-13 18:01:22,400000180,Eric,Bower,New Hampshire,6697166886,Coat,159.80,0.06
...,...,...,...,...,...,...,...,...,...,...
3450,109805,2016-12-10 18:08:49,200000662,Trevor,Skinner,Louisiana,4619440506,Shorts,69.75,0.10
3451,109804,2016-12-10 18:08:36,100000854,Carl,Clark,Kentucky,5153370805,Shorts,43.96,0.02
3452,109803,2016-12-10 18:08:24,200000793,Charles,McDonald,Utah,3123824581,Sweatpants,43.89,0.06
3453,109802,2016-12-10 18:08:03,200000263,Gabrielle,Marshall,Michigan,9195451761,Hand Towel,51.66,0.07
3454,109801,2016-12-10 18:07:25,200000670,Richard,Carr,Louisiana,6660530324,Washcloth,35.14,0.05

In [15]:
df.iloc[[3, 5], 3]

3    Dorothy
5     Joshua
Name: name, dtype: object

In [16]:
for column in df.columns:
    print(column)

transactionid
timestamp
customerid
name
surname
shipping_state
item
description
retail_price
loyalty_discount

In [17]:
df.customerid

0       200000663
1       200000661
2       200000662
3       100000007
4       400000180
          ...
3450    200000662
3451    100000854
3452    200000793
3453    200000263
3454    200000670
Name: customerid, Length: 3455, dtype: int64

In [18]:
df['customerid'].xs(5)

200000701

In [19]:
df

,transactionid,timestamp,customerid,name,surname,shipping_state,item,description,retail_price,loyalty_discount
0,113255,2016-12-13 18:05:37,200000663,Leonard,Jackson,Delaware,8619953091,Pillowcase,18.96,0.02
1,113254,2016-12-13 18:05:22,200000661,Lucas,Abraham,Louisiana,2020397001,Men's Pajama Set,23.10,0.00
2,113253,2016-12-13 18:03:57,200000662,Trevor,Skinner,Louisiana,4681342313,Sheets,29.90,0.10
3,113252,2016-12-13 18:01:45,100000007,Dorothy,Thomson,Alabama,6697166886,Coat,159.80,0.07
4,113251,2016-12-13 18:01:22,400000180,Eric,Bower,New Hampshire,6697166886,Coat,159.80,0.06
...,...,...,...,...,...,...,...,...,...,...
3450,109805,2016-12-10 18:08:49,200000662,Trevor,Skinner,Louisiana,4619440506,Shorts,69.75,0.10
3451,109804,2016-12-10 18:08:36,100000854,Carl,Clark,Kentucky,5153370805,Shorts,43.96,0.02
3452,109803,2016-12-10 18:08:24,200000793,Charles,McDonald,Utah,3123824581,Sweatpants,43.89,0.06
3453,109802,2016-12-10 18:08:03,200000263,Gabrielle,Marshall,Michigan,9195451761,Hand Towel,51.66,0.07
3454,109801,2016-12-10 18:07:25,200000670,Richard,Carr,Louisiana,6660530324,Washcloth,35.14,0.05

In [20]:
(df.retail_price.add(100)/3).round(2)

0       39.65
1       41.03
2       43.30
3       86.60
4       86.60
        ...
3450    56.58
3451    47.99
3452    47.96
3453    50.55
3454    45.05
Name: retail_price, Length: 3455, dtype: float64

In [21]:
df

,transactionid,timestamp,customerid,name,surname,shipping_state,item,description,retail_price,loyalty_discount
0,113255,2016-12-13 18:05:37,200000663,Leonard,Jackson,Delaware,8619953091,Pillowcase,18.96,0.02
1,113254,2016-12-13 18:05:22,200000661,Lucas,Abraham,Louisiana,2020397001,Men's Pajama Set,23.10,0.00
2,113253,2016-12-13 18:03:57,200000662,Trevor,Skinner,Louisiana,4681342313,Sheets,29.90,0.10
3,113252,2016-12-13 18:01:45,100000007,Dorothy,Thomson,Alabama,6697166886,Coat,159.80,0.07
4,113251,2016-12-13 18:01:22,400000180,Eric,Bower,New Hampshire,6697166886,Coat,159.80,0.06
...,...,...,...,...,...,...,...,...,...,...
3450,109805,2016-12-10 18:08:49,200000662,Trevor,Skinner,Louisiana,4619440506,Shorts,69.75,0.10
3451,109804,2016-12-10 18:08:36,100000854,Carl,Clark,Kentucky,5153370805,Shorts,43.96,0.02
3452,109803,2016-12-10 18:08:24,200000793,Charles,McDonald,Utah,3123824581,Sweatpants,43.89,0.06
3453,109802,2016-12-10 18:08:03,200000263,Gabrielle,Marshall,Michigan,9195451761,Hand Towel,51.66,0.07
3454,109801,2016-12-10 18:07:25,200000670,Richard,Carr,Louisiana,6660530324,Washcloth,35.14,0.05

In [25]:
df.dtypes

transactionid                int64
timestamp           datetime64[ns]
customerid                   int64
name                        object
surname                     object
shipping_state              object
item                         int64
description                 object
retail_price               float64
loyalty_discount           float64
dtype: object

In [28]:
df['retail_price'].corr(df['loyalty_discount']).round(4)

0.0142

In [31]:
df['retail_price'].autocorr(lag=1)

0.0006352011114111554

In [33]:
df['loyalty_discount'].autocorr(lag=2)

0.036245162370359796

In [34]:
df['loyalty_discount'].skew()

0.022494928302584864

In [35]:
df['loyalty_discount'].kurtosis()

-1.2703659158710303

In [4]:
file = 'https://raw.githubusercontent.com/MicrosoftLearning/dp-data/main/sales.csv'

In [7]:
df = pd.read_csv(file)
df

,SalesOrderNumber,SalesOrderLineNumber,OrderDate,CustomerName,EmailAddress,Item,Quantity,UnitPrice,TaxAmount
0,SO43701,1,2019-07-01,Christy Zhu,christy12@adventure-works.com,"Mountain-100 Silver, 44",1,3399.9900,271.9992
1,SO43704,1,2019-07-01,Julio Ruiz,julio1@adventure-works.com,"Mountain-100 Black, 48",1,3374.9900,269.9992
2,SO43705,1,2019-07-01,Curtis Lu,curtis9@adventure-works.com,"Mountain-100 Silver, 38",1,3399.9900,271.9992
3,SO43700,1,2019-07-01,Ruben Prasad,ruben10@adventure-works.com,"Road-650 Black, 62",1,699.0982,55.9279
4,SO43703,1,2019-07-01,Albert Alvarez,albert7@adventure-works.com,"Road-150 Red, 62",1,3578.2700,286.2616
...,...,...,...,...,...,...,...,...,...
32713,SO63093,2,2021-12-31,Rebekah Martin,rebekah20@adventure-works.com,Patch Kit/8 Patches,1,2.2900,0.1832
32714,SO63113,1,2021-12-31,Carolyn Alonso,carolyn29@adventure-works.com,"Road-550-W Yellow, 48",1,1120.4900,89.6392
32715,SO63113,2,2021-12-31,Carolyn Alonso,carolyn29@adventure-works.com,"Short-Sleeve Classic Jersey, S",1,53.9900,4.3192
32716,SO63066,1,2021-12-31,Teresa Navarro,teresa10@adventure-works.com,Mountain Tire Tube,1,4.9900,0.3992
32717,SO63066,2,2021-12-31,Teresa Navarro,teresa10@adventure-works.com,Patch Kit/8 Patches,1,2.2900,0.1832

In [8]:
df.to_csv('sales.csv', index=False)