### Data Sources

In [1]:
import fda_toolkit as fda
import pandas as pd
import numpy as np
from onedrive_loader import files, load

In [2]:
# Set multiple display options
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [3]:
import fda_toolkit as ftk
print(ftk.__version__)  # Should show 0.4.1 or later

0.4.1

In [4]:
files()

['financial_transactions_dataset_analytics_kaggle',
 'powerbI_data_lakehouse',
 'region_electric_hourly_time_series',
 'sundry_data_sources']

____

In [24]:
df = load("sundry_data_sources", "uk_smoking_data.csv")
df

,gender,age,marital_status,highest_qualification,nationality,ethnicity,gross_income,region,smoke,amt_weekends,amt_weekdays,type
0,Male,38,Divorced,No Qualification,British,White,"2,600 to 5,200",The North,No,NaN,NaN,NaN
1,Female,42,Single,No Qualification,British,White,"Under 2,600",The North,Yes,12.0,12.0,Packets
2,Male,40,Married,Degree,English,White,"28,600 to 36,400",The North,No,NaN,NaN,NaN
3,Female,40,Married,Degree,English,White,"10,400 to 15,600",The North,No,NaN,NaN,NaN
4,Female,39,Married,GCSE/O Level,British,White,"2,600 to 5,200",The North,No,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1686,Male,22,Single,No Qualification,Scottish,White,"2,600 to 5,200",Scotland,No,NaN,NaN,NaN
1687,Female,49,Divorced,Other/Sub Degree,English,White,"2,600 to 5,200",Scotland,Yes,20.0,20.0,Hand-Rolled
1688,Male,45,Married,Other/Sub Degree,Scottish,White,"5,200 to 10,400",Scotland,No,NaN,NaN,NaN
1689,Female,51,Married,No Qualification,English,White,"2,600 to 5,200",Scotland,Yes,20.0,20.0,Packets
1690,Male,31,Married,Degree,Scottish,White,"10,400 to 15,600",Scotland,No,NaN,NaN,NaN

___

In [6]:
fda.info()

In [7]:
# Filter by category
fda.info('core')

In [8]:
# Filter by module
fda.info('finance')

In [9]:
# Filter by category
fda.info('features')

In [10]:
# Filter by category
fda.info('validation')

In [11]:
# Filter by module
fda.info('Reporting')

---

### Uisng the Core Function

In [25]:
df

,gender,age,marital_status,highest_qualification,nationality,ethnicity,gross_income,region,smoke,amt_weekends,amt_weekdays,type
0,Male,38,Divorced,No Qualification,British,White,"2,600 to 5,200",The North,No,NaN,NaN,NaN
1,Female,42,Single,No Qualification,British,White,"Under 2,600",The North,Yes,12.0,12.0,Packets
2,Male,40,Married,Degree,English,White,"28,600 to 36,400",The North,No,NaN,NaN,NaN
3,Female,40,Married,Degree,English,White,"10,400 to 15,600",The North,No,NaN,NaN,NaN
4,Female,39,Married,GCSE/O Level,British,White,"2,600 to 5,200",The North,No,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1686,Male,22,Single,No Qualification,Scottish,White,"2,600 to 5,200",Scotland,No,NaN,NaN,NaN
1687,Female,49,Divorced,Other/Sub Degree,English,White,"2,600 to 5,200",Scotland,Yes,20.0,20.0,Hand-Rolled
1688,Male,45,Married,Other/Sub Degree,Scottish,White,"5,200 to 10,400",Scotland,No,NaN,NaN,NaN
1689,Female,51,Married,No Qualification,English,White,"2,600 to 5,200",Scotland,Yes,20.0,20.0,Packets
1690,Male,31,Married,Degree,Scottish,White,"10,400 to 15,600",Scotland,No,NaN,NaN,NaN

In [16]:
ftk.info('core')

In [21]:
from fda_toolkit import core
dir(core)

['__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'cap_outliers',
 'classify_columns',
 'clean_boolean_column',
 'clean_categorical_column',
 'clean_column_headers',
 'clean_date_column',
 'clean_numeric_column',
 'clean_text_column',
 'coerce_empty_to_nan',
 'columns',
 'combine_columns',
 'convert_data_types',
 'convert_date_columns',
 'deduplicate_by_priority',
 'detect_outliers_iqr',
 'drop_constant_columns',
 'drop_empty_columns',
 'drop_empty_rows',
 'drop_missing_required',
 'drop_sparse_columns',
 'drop_sparse_rows',
 'duplicates',
 'fill_missing',
 'filter_by_date_range',
 'filter_by_value_range',
 'filter_rows',
 'find_duplicates',
 'flag_outliers',
 'make_unique_columns',
 'missing',
 'outliers',
 'remove_duplicates',
 'remove_outliers_iqr',
 'remove_outliers_zscore',
 'remove_repeated_headers',
 'remove_summary_rows',
 'rename_columns',
 'reorder_columns',
 'rows',
 'select_columns',
 'select_columns_by_type',
 'split_column',
 'standardize_text_values',
 'text',
 'trim_leading_trailing_rows',
 'types',
 'winsorize_outliers']

In [26]:
df = core.clean_column_headers(df)
df.head()

,gender,age,marital_status,highest_qualification,nationality,ethnicity,gross_income,region,smoke,amt_weekends,amt_weekdays,type
0,Male,38,Divorced,No Qualification,British,White,"2,600 to 5,200",The North,No,NaN,NaN,NaN
1,Female,42,Single,No Qualification,British,White,"Under 2,600",The North,Yes,12.0,12.0,Packets
2,Male,40,Married,Degree,English,White,"28,600 to 36,400",The North,No,NaN,NaN,NaN
3,Female,40,Married,Degree,English,White,"10,400 to 15,600",The North,No,NaN,NaN,NaN
4,Female,39,Married,GCSE/O Level,British,White,"2,600 to 5,200",The North,No,NaN,NaN,NaN

In [22]:
# Add this to a cell and run it
%pip install --upgrade fda-toolkit

/Users/teslim/TeslimWorkSpace/Modules/Modules-1-Python/.venv/bin/python: No module named pip
Note: you may need to restart the kernel to use updated packages.